# Generated by Django 5.1.7 on 2025-03-27 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category Name', max_length=100, verbose_name='Name')),
                ('description', models.TextField(help_text='Description', verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product Name', max_length=100, verbose_name='Name')),
                ('price', models.FloatField(help_text='Price', verbose_name='Price')),
                ('description', models.TextField(help_text='Description', verbose_name='Description')),
                ('image', models.ImageField(blank=True, help_text='Image', null=True, upload_to='images/', verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date Added', null=True, verbose_name='Date Added')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date Last Modified', null=True, verbose_name='Date Last Modified')),
                ('category', models.ForeignKey(help_text='Category', on_delete=django.db.models.deletion.CASCADE, to='catalog.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
